nav:
  - 🏡 Home: ./index.md


site_name: Comitiva Esperança
repo_url: https://github.com/comitivaesperanca/docs/
repo_name: comitivaesperanca
edit_uri: edit/main/docs/

theme:
  logo: https://avatars.githubusercontent.com/u/129684075
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
 

  extra_css:
    - ./stylesheet/extra.css

extra:
  generator: true

plugins:
  - git-revision-date
  - search
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes