site_name: Comitiva Esperança
repo_url: https://github.com/comitivaesperanca/docs/
repo_name: comitivaesperanca
edit_uri: edit/main/docs/

theme:
  logo: https://avatars.githubusercontent.com/u/129684075
  name: material
      
  extra_css:
    - extra.css

  palette: 
    primary: 'orange'
    accent: 'orange'
    primary-bg: 'white'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
 
  font:
    text: Nunito
    code: Fira Code
extra:
  generator: true

plugins:
  - git-revision-date
  - search
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      title: Índice